### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by arthi-j** [awslabs/aws-cognito-apigw-angular-auth#15] opened 2018-05-31 01:26 UTC
I get the error "Cannot read property 'config' of null" on npm start. 

This is not the same as https://github.com/aws-samples/aws-cognito-apigw-angular-auth/issues/14. I am in a different directory. I ended up creating the `.angular-cli.json` file manually and worked after that.

Here is the output go `ng --version`

```
Your global Angular CLI version (6.0.7) is greater than your local
version (1.0.0). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 10.3.0
os: darwin x64
@angular/animations: 4.4.7
@angular/cdk: 2.0.0-beta.12
@angular/common: 4.4.7
@angular/compiler: 4.4.7
@angular/core: 4.4.7
@angular/forms: 4.4.7
@angular/http: 4.4.7
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.4.7
@angular/platform-browser-dynamic: 4.4.7
@angular/router: 4.4.7
@angular/cli: 1.0.0
@angular/compiler-cli: 4.4.7
```

**Comment by Sarazh** [comment] 2018-06-14 14:01
I also faced the same problems, which is solved by install `npm install -g @angular/cli@1.0.0`.  I think the problem is that the global @angular/cli is incompatible with local one. The newest version uses `angular.json` instead of `.angular-cli.json`.

**Comment by trilom** [comment] 2018-06-15 16:49
I got to this same fuggin point.  Read through the install instructions and realized that the version here was being installed, then creating the project which mucks up the whole structure.

**Comment by KoldBrewEd** [comment] 2018-07-02 01:07
Merged, thanks for the help

**Closed as completed by KoldBrewEd** 2018-07-02 01:07 UTC
